name: Code Scan
description: Run security repo precommit scan on push
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run  echo "Github workspace is ${{ github.workspace }}."
      #- name: Check out repository code
      #  uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "This job's status is ${{ job.status }}."
      - name: Checkout security repository as a directory parallel to this repo
        run: git clone https://The-OpenROAD-Project/security.git ../security
      - name: List files in the repository after security clone
        run: ls ${{ github.workspace }}
      - name: run the security scanning py script
        run: ../security/git/hooks/pre-commit.py --local
