name: Code Scan
description: Run security repo precommit scan on push
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Checkout security repository as a directory parallel to this repo
        run: git clone https://The-OpenROAD-Project/security.git ../security
      - name: run the security scanning py script
        run: ../security/git/hooks/pre-commit.py --local
