name: Push to repository.

inputs:
  owner:
    description: GitHub username who owns the repository.
    default: ${{ github.event.repository.owner.name }}
  repo:
    description: GitHub repo name.
    default: ${{ github.event.repository.name }}
  branch:
    description: Branch to push.
    default: ${{ github.head_ref }}
  force:
    description: Should the push be forced?
    default: false
  deployKey:
    description: SSH private "deploy key" which has write access to staging repository.
    required: true

runs:
  using: composite

  steps:

  - name: Pushing ${{ inputs.branch }} to ${{ inputs.slug }}
    shell: bash
    run: |

      if [[ -z "${{ inputs.owner }}"     ]]; then echo "Missing owner value!"; exit 1; fi
      if [[ -z "${{ inputs.repo }}"      ]]; then echo "Missing repo value!"; exit 1; fi
      if [[ -z "${{ inputs.branch }}"    ]]; then echo "Missing branch value!"; exit 1; fi
      if [[ -z "${{ inputs.deployKey }}" ]]; then echo "Missing deployKey value!"; exit 1; fi

      # Configure ssh to ignore host key checking.
      rm -rf ~/.ssh
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh

      cat > ~/.ssh/config << EOF
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
      EOF

      # Start ssh agent and add deploy key.
      eval $(ssh-agent -s)
      ssh-add - <<< "${{ inputs.deployKey }}"

      # Figure out if we should do a force push
      export GIT_ARGS=''
      if [[ x${{ inputs.force }} = 'xtrue' ]]; then
        export GIT_ARGS=--force
      fi

      # Add local repository and push to it.
      git remote add origin git+ssh://git@github.com/${{ inputs.owner }}/${{ inputs.repo }}.git
      git push $GIT_ARGS origin --verbose ${{ inputs.branch }}
