name: Create a new pull request.

inputs:
  draft:
    description: Open the pull request as a draft.
    required: false
    default: 'false'

outputs:
  pr:
    description: Pull request ID number.
    value: ${{ steps.send_pr.outputs.pr }}

runs:
  using: composite

  steps:

  - id: send_pr
    name: Creating PR is needed.
    shell: bash
    env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_DRAFT: ${{ inputs.draft }}
    run: $GITHUB_ACTION_PATH/action.py
